### ISSUE TITLE
了

### ISSUE THREAD

**Issue by lalafire520** [Liquor030/Sub_Ruleset#1]

**Comment by Zhuliyer** [comment]
您好作者 ，您的皮皮虾去水印的脚本失效了 我在更新皮皮虾app之后  水印无法去除 望作者大大更新下作为皮友的我 感激不尽

**Comment by Bearxxuan** [comment]
经测试，暂未失效，如果你有什么特殊情况可以联系我的tg: https://t.me/Liquor030
